[package]
name = "ff-node-monitor"
version = "0.1.0"
authors = ["Ralf Jung <post@ralfj.de>"]

[dependencies]
rocket = "0.3.10"
rocket_codegen = "0.3.10"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["handlebars_templates"]
