[package]
name = "ff-node-monitor"
version = "0.1.0"
authors = ["Ralf Jung <post@ralfj.de>"]

[dependencies]
rocket = "0.3.10"
rocket_codegen = "0.3.10"
rocket_contrib = { version = "*", features = ["handlebars_templates"] }
diesel = { version = "1.2.2", features = ["postgres"] }
diesel_migrations = "1.2.0"
r2d2 = "0.8.2"
r2d2-diesel = "1.0.0"
ring = "0.11.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rmp-serde = "0.13.7"
failure = "0.1.1"
url = "1.7.0"
url_serde = "0.2.0"
toml = "0.4.6"
lettre = "0.8"
lettre_email = "0.8"
