[package]
name = "ff-node-monitor"
version = "0.1.0"
authors = ["Ralf Jung <post@ralfj.de>"]
edition = "2018"

[dependencies]
rocket = "0.3.10"
rocket_codegen = "*"
rocket_contrib = { version = "*", features = ["handlebars_templates"] }
diesel = { version = "1.3.0", features = ["postgres"] }
diesel_migrations = "*"
r2d2 = "0.8.2"
r2d2-diesel = "1.0.0"
ring = "0.11.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rmp-serde = "0.13.7"
failure = "0.1.1"
url = "1.7.0"
url_serde = "0.2.0"
toml = "0.4.6"
base64 = "0.10"
hex = "0.3.2"
reqwest = "0.9"
chrono = { version = "0.4.2", features = ["serde"] }

[dependencies.lettre]
git = "https://github.com/lettre/lettre"
rev = "644b1e59b06704822c6a540c12ed44b6e827d221"
features = ["smtp-transport"]

[dependencies.lettre_email]
git = "https://github.com/lettre/lettre"
rev = "644b1e59b06704822c6a540c12ed44b6e827d221"
